Extraer los archivos del dataset SOCO

In [12]:
import pandas as pd
import numpy as np

Cargamos los paths de los archivos csv

In [13]:
train_csv = "C:\\Users\\rodri\\OneDrive\\Documentos\\8vo\\Plagiarism-Dettection\\AI-SOCO-master\\data_dir\\train.csv"
test_csv = "C:\\Users\\rodri\\OneDrive\\Documentos\\8vo\\Plagiarism-Dettection\\AI-SOCO-master\\data_dir\\unlabeled_test.csv"
dev_csv = "C:\\Users\\rodri\\OneDrive\\Documentos\\8vo\\Plagiarism-Dettection\\AI-SOCO-master\\data_dir\\dev.csv"

sacar lso uid y pid

In [14]:
train_df = pd.read_csv(train_csv)
test_df = pd.read_csv(test_csv)
val_df = pd.read_csv(dev_csv)
train_df.head()

   uid    pid
0  415  27909
1  415  55938
2  415  90936
3  415  56858
4  415   9447

In [15]:
val_df.head()

   uid    pid
0  415  12180
1  415  67901
2  415  76245
3  415  70953
4  415  41256

In [16]:
path = "C:\\Users\\rodri\\OneDrive\\Documentos\\8vo\\Plagiarism-Dettection\\AI-SOCO-master\\data_dir\\train"
for index, row in train_df.iterrows():
    train_df.loc[index, 'code'] = open(f"{path}/{row['pid']}", encoding='utf-8').read()
    

train_df.head()

   uid    pid                                               code
0  415  27909  /*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...
1  415  55938  /*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...
2  415  90936  /*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...
3  415  56858  /*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...
4  415   9447  /*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...

In [17]:
path1 = "C:\\Users\\rodri\\OneDrive\\Documentos\\8vo\\Plagiarism-Dettection\\AI-SOCO-master\\data_dir\\dev"
for index, row in val_df.iterrows():
    val_df.loc[index, 'code'] = open(f"{path1}/{row['pid']}", encoding='utf-8').read()
    

val_df.head()

   uid    pid                                               code
0  415  12180  /*{{{*/\n#include <bits/stdc++.h>\n#define SZ(...
1  415  67901  /*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...
2  415  76245  /*{{{*/\n#include <bits/stdc++.h>\n#define SZ(...
3  415  70953  /*{{{*/\n#include <bits/stdc++.h>\n#define SZ(...
4  415  41256  /*{{{*/\n#include <bits/stdc++.h>\n#define SZ(...

In [19]:
path2 = "C:\\Users\\rodri\\OneDrive\\Documentos\\8vo\\Plagiarism-Dettection\\AI-SOCO-master\\data_dir\\test"
for index, row in test_df.iterrows():
    pid = int(row['pid'])
    test_df.loc[index, 'code'] = open(f"{path2}/{pid}", encoding='utf-8').read()
    

test_df.head()

   uid    pid                                               code
0  NaN  34841  ///If I see that thing, I'ma squash it\n///and...
1  NaN  68320  /*input\n1\n1\n\n*/\n \n/*\n                  ...
2  NaN  72734  #include <algorithm>\n#include <iostream>\n#in...
3  NaN  55803  //HASHEMESHOON hastam ;)\n#include <iostream>\...
4  NaN  96166  #include <functional>\n#include <algorithm>\n#...

Función de Limpieza de código

In [20]:
def clean_code(code):
    # Eliminar caracteres que no sean utf-8
    code = code.encode('utf-8', errors='ignore').decode('utf-8')
    
    return code

In [21]:
train_df['clean_code'] = train_df['code'].apply(clean_code)
val_df['clean_code'] = val_df['code'].apply(clean_code)
test_df['clean_code'] = test_df['code'].apply(clean_code)

In [22]:
train_df.to_csv("train_clean.csv", index=False)
val_df.to_csv("val_clean.csv", index=False)
test_df.to_csv("test_clean.csv", index=False)