Extraer los archivos del dataset SOCO

In [1]:
import pandas as pd
import numpy as np

Cargamos los paths de los archivos csv

In [2]:
train_csv = "C:\\Users\\rodri\\OneDrive\\Documentos\\8vo\\Plagiarism-Dettection\\AI-SOCO-master\\data_dir\\train.csv"
test_csv = "C:\\Users\\rodri\\OneDrive\\Documentos\\8vo\\Plagiarism-Dettection\\AI-SOCO-master\\data_dir\\unlabeled_test.csv"
dev_csv = "C:\\Users\\rodri\\OneDrive\\Documentos\\8vo\\Plagiarism-Dettection\\AI-SOCO-master\\data_dir\\dev.csv"

sacar lso uid y pid

In [3]:
train_df = pd.read_csv(train_csv)
test_df = pd.read_csv(test_csv)
val_df = pd.read_csv(dev_csv)
train_df.head()

   uid    pid
0  415  27909
1  415  55938
2  415  90936
3  415  56858
4  415   9447

In [6]:
val_df.head()

   uid    pid                                               code
0  415  12180  /*{{{*/\n#include <bits/stdc++.h>\n#define SZ(...
1  415  67901                                                NaN
2  415  76245                                                NaN
3  415  70953                                                NaN
4  415  41256                                                NaN

In [4]:
path = "C:\\Users\\rodri\\OneDrive\\Documentos\\8vo\\Plagiarism-Dettection\\AI-SOCO-master\\data_dir\\train"
for index, row in train_df.iterrows():
    train_df.loc[index, 'code'] = open(f"{path}/{row['pid']}", encoding='utf-8').read()
    

train_df.head()

   uid    pid                                               code
0  415  27909  /*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...
1  415  55938  /*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...
2  415  90936  /*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...
3  415  56858  /*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...
4  415   9447  /*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...

In [5]:
path1 = "C:\\Users\\rodri\\OneDrive\\Documentos\\8vo\\Plagiarism-Dettection\\AI-SOCO-master\\data_dir\\dev"
for index, row in val_df.iterrows():
    val_df.loc[index, 'code'] = open(f"{path1}/{row['pid']}", encoding='utf-8').read()
    

val_df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rodri\\OneDrive\\Documentos\\8vo\\Plagiarism-Dettection\\AI-SOCO-master\\data_dir\\dev/67901'

In [ ]:
path2 = "C:\\Users\\rodri\\OneDrive\\Documentos\\8vo\\Plagiarism-Dettection\\AI-SOCO-master\\data_dir\\test"
for index, row in val_df.iterrows():
    val_df.loc[index, 'code'] = open(f"{path2}/{row['pid']}", encoding='utf-8').read()
    

val_df.head()

Función de Limpieza de código

In [ ]:
def clean_code(code):
    # Eliminar caracteres que no sean utf-8
    code = code.encode('utf-8', errors='ignore').decode('utf-8')
    
    return code

In [ ]:
train_df['clean_code'] = train_df['code'].apply(clean_code)
val_df['clean_code'] = val_df['code'].apply(clean_code)
test_df['clean_code'] = test_df['code'].apply(clean_code)

In [ ]:
train_df.to_csv("train_clean.csv", index=False)
val_df.to_csv("val_clean.csv", index=False)
test_df.to_csv("test_clean.csv", index=False)