Extraer los archivos del dataset SOCO

In [ ]:
import pandas as pd
import numpy as np

Cargamos los paths de los archivos csv

In [15]:
train_csv = "C:\\Users\\rodri\\OneDrive\\Documentos\\8vo\\Plagiarism-Dettection\\AI-SOCO-master\\data_dir\\train.csv"
test_csv = "C:\\Users\\rodri\\OneDrive\\Documentos\\8vo\\Plagiarism-Dettection\\AI-SOCO-master\\data_dir\\test.csv"

sacar lso uid y pid

In [16]:
train_df = pd.read_csv(train_csv)
test_df = pd.read_csv(test_csv)
train_df.head()

   uid    pid
0  415  27909
1  415  55938
2  415  90936
3  415  56858
4  415   9447

In [17]:
path = "C:\\Users\\rodri\\OneDrive\\Documentos\\8vo\\Plagiarism-Dettection\\AI-SOCO-master\\data_dir\\train"
for index, row in train_df.iterrows():
    train_df.loc[index, 'code'] = open(f"{path}/{row['pid']}", encoding='utf-8').read()
    

train_df.head()

   uid    pid                                               code
0  415  27909  /*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...
1  415  55938  /*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...
2  415  90936  /*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...
3  415  56858  /*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...
4  415   9447  /*{{{*/\n#include<cstdio>\n#include<cstdlib>\n...

Función de Limpieza de código

In [ ]:
def clean_code(code):
    # Eliminar comentarios
    code = re.sub(r'//.*|/\*[\s\S]*?\*/', '', code)
    # Eliminar espacios en blanco adicionales
    code = re.sub(r'[ ]+', ' ', code).strip()
    return code